# Port du serveur web embarqu\uFFFD
server.port=8080

# Nom de l'application (visible dans les logs)
spring.application.name=gestion-pharmacie

# Configuration email (alertes stock critique)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pharmacie.gestion.stage@gmail.com
spring.mail.password=eimg groc kmqa ixhv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true